# Generated by Django 4.0.4 on 2022-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
