# Generated by Django 4.0.4 on 2022-05-11 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_review_dislikes_alter_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
